module.exports = {
  apps: [
    {
      name: 'qvor',
      script: 'node_modules/.bin/next',
      args: 'start',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '700M',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      kill_timeout: 10000,
      wait_ready: true,
      listen_timeout: 15000,
      out_file: './logs/out.log',
      error_file: './logs/error.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'qvor-ws',
      script: 'node_modules/.bin/tsx',
      args: 'scripts/ws-signal.ts',
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '100M',
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
        WS_PORT: 3001,
      },
      out_file: './logs/ws-out.log',
      error_file: './logs/ws-error.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'qvor-bot',
      script: 'node_modules/.bin/tsx',
      args: 'scripts/bot.ts',
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '150M',
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
      },
      out_file: './logs/bot-out.log',
      error_file: './logs/bot-error.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
}
